; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs < %s -relocation-model=pic -code-model=large | FileCheck %s
; RUN: llc -verify-machineinstrs < %s -relocation-model=static -code-model=large | FileCheck %s
; RUN: llc -verify-machineinstrs < %s -relocation-model=pic -code-model=large -filetype=obj
; RUN: llc -verify-machineinstrs < %s -relocation-model=static -code-model=large -filetype=obj

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@abs_sym = external hidden global [0 x i8], !absolute_symbol !0
@abs_sym_in_range = external hidden global [0 x i8], !absolute_symbol !1
@abs_sym_8bit = external hidden global [0 x i8], !absolute_symbol !2

define i64 @func_abs_sym() nounwind {
; CHECK-LABEL: func_abs_sym:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $abs_sym, %rax
; CHECK-NEXT:    retq
  %1 = ptrtoint ptr @abs_sym to i64
  ret i64 %1
}

define i64 @func_abs_sym_in_range() nounwind {
; CHECK-LABEL: func_abs_sym_in_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $abs_sym_in_range, %rax
; CHECK-NEXT:    retq
  %1 = ptrtoint ptr @abs_sym_in_range to i64
  ret i64 %1
}

define void @func_abs_sym_8bit(ptr %x) nounwind {
; CHECK-LABEL: func_abs_sym_8bit:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $abs_sym_8bit@ABS8, (%rdi)
; CHECK-NEXT:    je .LBB2_1
; CHECK-NEXT:  # %bb.2: # %if.then
; CHECK-NEXT:    jmpq *xf@GOTPCREL(%rip) # TAILCALL
; CHECK-NEXT:  .LBB2_1: # %if.end
; CHECK-NEXT:    retq
  %val = load i8, ptr %x, align 1
  %ext = sext i8 ptrtoint (ptr @abs_sym_8bit to i8) to i32
  %conv = sext i8 %val to i32
  %and = and i32 %conv, %ext
  %tobool = icmp eq i32 %and, 0
  br i1 %tobool, label %if.end, label %if.then
if.then:
  tail call void @xf()
  br label %if.end
if.end:
  ret void
}

declare void @xf()

!0 = !{i64 -1, i64 -1}
!1 = !{i64 -2147483648, i64 2147483648}
!2 = !{i64 0, i64 128}
