; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc -verify-machineinstrs < %s -code-model=large -relocation-model=pic -mtriple=x86_64--linux | FileCheck %s

@.str = private unnamed_addr constant [2 x i8] c"a\00", align 1

define void @pr38385() {
; CHECK-LABEL: pr38385:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl .L.str@GOTPCREL(%rip), %eax
; CHECK-NEXT:    movb %al, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    retq
  %p = alloca i8, align 1
  store i8 ptrtoint (ptr @.str to i8), ptr %p, align 1
  ret void
}
