; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s | FileCheck %s --check-prefix=CHECK-SMALL
; RUN: llc --code-model=medium -large-data-threshold=100 < %s | FileCheck %s --check-prefix=CHECK-SMALL
; RUN: llc --code-model=medium < %s | FileCheck %s --check-prefix=CHECK-MEDIUM
; RUN: llc --code-model=large -large-data-threshold=100 < %s | FileCheck %s --check-prefix=CHECK-LARGE
; RUN: llc --code-model=large < %s | FileCheck %s --check-prefix=CHECK-LARGE
; RUN: llc --code-model=kernel < %s | FileCheck %s --check-prefix=CHECK-SMALL

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@a = external dso_local global i32, align 4

declare void @f()

define void @foo(i64 %b) {
; CHECK-SMALL-LABEL: foo:
; CHECK-SMALL:       # %bb.0: # %entry
; CHECK-SMALL-NEXT:    cmpq $a, %rdi
; CHECK-SMALL-NEXT:    je f@PLT # TAILCALL
; CHECK-SMALL-NEXT:  # %bb.1: # %if.end
; CHECK-SMALL-NEXT:    retq
;
; CHECK-MEDIUM-LABEL: foo:
; CHECK-MEDIUM:       # %bb.0: # %entry
; CHECK-MEDIUM-NEXT:    movabsq $a, %rax
; CHECK-MEDIUM-NEXT:    cmpq %rax, %rdi
; CHECK-MEDIUM-NEXT:    je f@PLT # TAILCALL
; CHECK-MEDIUM-NEXT:  # %bb.1: # %if.end
; CHECK-MEDIUM-NEXT:    retq
;
; CHECK-LARGE-LABEL: foo:
; CHECK-LARGE:       # %bb.0: # %entry
; CHECK-LARGE-NEXT:    cmpq a@GOTPCREL(%rip), %rdi
; CHECK-LARGE-NEXT:    jne .LBB0_1
; CHECK-LARGE-NEXT:  # %bb.2: # %if.then
; CHECK-LARGE-NEXT:    jmpq *f@GOTPCREL(%rip) # TAILCALL
; CHECK-LARGE-NEXT:  .LBB0_1: # %if.end
; CHECK-LARGE-NEXT:    retq
entry:
  %cmp = icmp eq i64 %b, ptrtoint (ptr @a to i64)
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @f()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

