; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-linux-gnu -tailcallopt -code-model=large -enable-misched=false | FileCheck %s

declare fastcc i32 @callee(i32 %arg)
define fastcc i32 @directcall(i32 %arg) {
; CHECK-LABEL: directcall:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    jmpq *callee@GOTPCREL(%rip) # TAILCALL
entry:
; This is the large code model, so &callee may not fit into the jmp
; instruction.  Instead, stick it into a register.
  %res = tail call fastcc i32 @callee(i32 %arg)
  ret i32 %res
}

; Check that the register used for an indirect tail call doesn't
; clobber any of the arguments.
define fastcc i32 @indirect_manyargs(ptr %target) {
; Adjust the stack to enter the function.  (The amount of the
; adjustment may change in the future, in which case the location of
; the stack argument and the return adjustment will change too.)
; CHECK-LABEL: indirect_manyargs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    movl $7, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movl $1, %edi
; CHECK-NEXT:    movl $2, %esi
; CHECK-NEXT:    movl $3, %edx
; CHECK-NEXT:    movl $4, %ecx
; CHECK-NEXT:    movl $5, %r8d
; CHECK-NEXT:    movl $6, %r9d
; CHECK-NEXT:    popq %r10
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    jmpq *%rax # TAILCALL
; Put the call target into R11, which won't be clobbered while restoring
; callee-saved registers and won't be used for passing arguments.
; Pass the stack argument.
; Pass the register arguments, in the right registers.
; Adjust the stack to "return".
; And tail-call to the target.
  %res = tail call fastcc i32 %target(i32 1, i32 2, i32 3, i32 4, i32 5,
                                      i32 6, i32 7)
  ret i32 %res
}

; Check that the register used for a direct tail call doesn't clobber
; any of the arguments.
declare fastcc i32 @manyargs_callee(i32,i32,i32,i32,i32,i32,i32)
define fastcc i32 @direct_manyargs() {
; Adjust the stack to enter the function.  (The amount of the
; adjustment may change in the future, in which case the location of
; the stack argument and the return adjustment will change too.)
; CHECK-LABEL: direct_manyargs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $7, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movl $1, %edi
; CHECK-NEXT:    movl $2, %esi
; CHECK-NEXT:    movl $3, %edx
; CHECK-NEXT:    movl $4, %ecx
; CHECK-NEXT:    movl $5, %r8d
; CHECK-NEXT:    movl $6, %r9d
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    jmpq *manyargs_callee@GOTPCREL(%rip) # TAILCALL
; Pass the stack argument.
; This is the large code model, so &manyargs_callee may not fit into
; the jmp instruction.  Put it into a register which won't be clobbered
; while restoring callee-saved registers and won't be used for passing
; arguments.
; Pass the register arguments, in the right registers.
; Adjust the stack to "return".
; And tail-call to the target.
  %res = tail call fastcc i32 @manyargs_callee(i32 1, i32 2, i32 3, i32 4,
                                               i32 5, i32 6, i32 7)
  ret i32 %res
}
